#!/bin/sh /etc/rc.common

USE_PROCD=1

START=99

extra_command "watch" "Watch currently configuration setups"
extra_command "remove" "Uninstall the program"

CONFIGURATION=flex-qdisc

start_service() {
    # Reading config
    config_load "${CONFIGURATION}"
    local device
    local interval
    local safety
    local download
    local upload
    local alpha
    local delta_download
    local delta_upload

    config_get device default device    
    config_get interval default interval    
    config_get safety default safety    
    config_get download default download    
    config_get upload default upload    
    config_get alpha default alpha    
    config_get delta_download default delta_download    
    config_get delta_upload default delta_upload

    # /etc/flex-qdisc/start >/dev/null 2>&1 &

    /etc/flex-qdisc/"${CONFIGURATION}" \
        "$device" \
        "$interval" \
        "$safety" \
        "$download" \
        "$upload" \
        "$alpha" \
        "$delta_download" \
        "$delta_upload" \
        >/dev/null 2>&1 &

    echo "Success flex-qdisc config setup!";
    echo
}

stop_service() {
    # Reading config
    config_load "${CONFIGURATION}"
    
    local device
    config_get device default device

    /etc/flex-qdisc/stop "$device"

    killall flex-qdisc 2>/dev/null
}

watch() {
    local STATE_FILE="/tmp/flex-qdisc.state"

    config_load "${CONFIGURATION}"

    local device interval safety
    local download upload alpha
    local delta_download delta_upload

    config_get device default device
    config_get interval default interval
    config_get safety default safety
    config_get download default download
    config_get upload default upload
    config_get alpha default alpha
    config_get delta_download default delta_download
    config_get delta_upload default delta_upload

    echo
    echo "=== Configured Values ==="
    echo "Device          : $device"
    echo "Interval        : $interval"
    echo "Safety          : $safety"
    echo "Download Floor  : ${download} Kbit"
    echo "Upload Floor    : ${upload} Kbit"
    echo "Alpha           : $alpha"
    echo "Delta Download  : $delta_download%"
    echo "Delta Upload    : $delta_upload%"

    echo
    echo "=== Last Applied ==="

    if [ -f "$STATE_FILE" ]; then
        . "$STATE_FILE"

        echo "Time            : $TIME"
        echo "Download        : $DL bps"
        echo "Upload          : $UL bps"
    else
        echo "No applied state found."
    fi

    echo
    echo "=== Current CAKE ==="
    tc -s qdisc show dev "$device"

    echo
    echo "=== Current IFB CAKE ==="
    tc -s qdisc show dev "ifb_$device"
}

remove() {
    /etc/flex-qdisc/remove
}