#!/bin/sh /etc/rc.common

START=99

start() {
    /usr/bin/flex-qdisc >/dev/null 2>&1 &
}

stop() {
    IFACE="${1:-phy0-sta0}"
    IFB="ifb_$IFACE"

    tc qdisc del dev ${IFACE} root 2>/dev/null
    tc qdisc del dev ${IFACE} ingress 2>/dev/null
    tc qdisc del dev ${IFB} root 2>/dev/null

    ip link set ${IFB} down 2>/dev/null
    ip link del ${IFB} 2>/dev/null


    killall flex-qdisc 2>/dev/null
}